### ISSUE TITLE
Refactor for Robot to become a Monolith

### ISSUE THREAD

**Issue by serafdev** [ccil-kbw/robot#10]
At the same time why not named it Masjid's Robot (or `MasjidsRobot` as slug)

Refactoring points:
- 1 entrypoint with a bunch of features
- Make it API based (+ generate a cli tool for flexibility while we work on some UI)

**Comment by serafdev** [comment]
This is currently running on ARM64 on Armbian using this docker compose file:

```yaml
version: '3'

services:
  
  monolith:
    image: ghcr.io/ccil-kbw/robot:latest-arm64
    restart: always
    ports:
      - 3333:3333

```

- Next for the release cycle we'll need to setup https://github.com/containrrr/watchtower to watch on that container for continuous delivery

- The supported feature ATM is the iqama-proxy, next on the list: discord-bot

**Comment by serafdev** [comment]
For the name I would prefer something simple like `mdroid` to simplif the cli naming:

- mdroid-cli
- mdroid-monolith
- mdroid-installer
- mdroid-updater

etc

**Comment by serafdev** [comment]
On the `docker-compose.yml` I added:

```yaml

  watchtower:
    image: containrrr/watchtower
    platform: linux/arm64
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600

```

That watches all containers and updates them when a new version is found, this only works if we continue pointing to `latest-arm64`

**Comment by serafdev** [comment]
Watchtower works great:

```sh
seraf@orangepi5:~/mdroid$ docker compose logs -f
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Watchtower 1.5.3"
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Using no notifications"
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Checking all containers (except explicitly disabled with label)"
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Scheduling first run: 2023-08-23 02:29:48 +0000 UTC"
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Note that the first check will be performed in 59 seconds"
mdroid-monolith-1    | Running iqama-proxy Go server on port :3333
mdroid-watchtower-1  | time="2023-08-23T02:29:50Z" level=info msg="Found new ghcr.io/ccil-kbw/robot:latest-arm64 image (19bd324f1ae7)"
mdroid-watchtower-1  | time="2023-08-23T02:29:50Z" level=info msg="Stopping /mdroid-monolith-1 (e9b7a4696912) with SIGTERM"
mdroid-monolith-1 exited with code 2
mdroid-watchtower-1  | time="2023-08-23T02:29:51Z" level=info msg="Creating /mdroid-monolith-1"
mdroid-watchtower-1  | time="2023-08-23T02:29:52Z" level=info msg="Session done" Failed=0 Scanned=2 Updated=1 notify=no
[...]
mdroid-monolith-1    | watchtower test: Running iqama-proxy Go server on port :3333
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Watchtower 1.5.3"
mdroid-watchtower-1  | time="2023-08-23T02:28:48Z" level=info msg="Using no notifications"

```

Switched to scanning every minute, let's monitor if too aggressive for a few weeks

**Comment by serafdev** [comment]
Adding a note on this MR for traceability:

```yaml
version: '3.7'

services:

  monolith:
    container_name: monolith
    image: ghcr.io/ccil-kbw/robot:latest
    restart: always
    environment:
      - MDROID_BOT_GUILD_ID=REDACTED
      - MDROID_BOT_TOKEN=REDACTED

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 120 monolith

```
